header_empresas = [
    "CNPJ BASICO", 
    "RAZAO SOCIAL / NOME EMPRESARIAL", 
    "NATUREZA JURIDICA", 
    "QUALIFICACAO DO RESPONSAVEL",
    "CAPITAL SOCIAL DA EMPRESA",
    "PORTE DA EMPRESA",
    "ENTE FEDERATIVO RESPONSÁVEL"
]

header_estabelecimentos = [
    "CNPJ BASICO", 
    "CNPJ ORDEM", 
    "CNPJ DV", 
    "IDENTIFICADOR MATRIZ/FILIAL",
    "NOME FANTASIA",
    "SITUACAO CADASTRAL",
    "DATA SITUACAO CADASTRAL",
    "MOTIVO SITUACAO CADASTRAL",
    "NOME DA CIDADE NO EXTERIOR",
    "PAIS",
    "DATA DE INICIO ATIVIDADE",
    "CNAE FISCAL PRINCIPAL",
    "CNAE FISCAL SECUNDARIA",
    "TIPO DE LOGRADOURO",
    "LOGRADOURO",
    "NUMERO",
    "COMPLEMENTO",
    "BAIRRO",
    "CEP",
    "UF",
    "MUNICIPIO",
    "DDD 1",
    "TELEFONE 1",
    "DDD 2",
    "TELEFONE 2",
    "DDD DO FAX",
    "FAX",
    "CORREIO ELETRONICO",
    "SITUACAO ESPECIAL",
    "DATA DA SITUACAO ESPECIAL"
]

header_socios = [
    "CNPJ BASICO", 
    "IDENTIFICADOR DE SOCIO", 
    "NOME DO SOCIO OU RAZÃO SOCIAL", 
    "CNPJ/CPF DO SOCIO",
    "QUALIFICAÇÃO DO SOCIO",
    "DATA DE ENTRADA SOCIEDADE",
    "PAIS",
    "REPRESENTANTE LEGAL",
    "NOME DO REPRESENTANTE",
    "QUALIFICACAO DO REPRESENTANTE LEGAL",
    "FAIXA ETARIA"
]